ALTER TABLE users
  ADD COLUMN IF NOT EXISTS rl_sec INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rl_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rl_block_until INT UNSIGNED NOT NULL DEFAULT 0;
